modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="rt"
version="1.0.0"
displayName="Red technology"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Dio, MCreator"

[[dependencies.rt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




